<?php

declare(strict_types=1);

return [
    // Setup
    'setup_title'      => 'Set up two-factor authentication',
    'setup_subtitle'   => 'Protect your account before continuing',
    'setup_intro'      => 'Use an authenticator app (Google Authenticator, Authy, 1Password, Microsoft Authenticator) to scan the QR code below.',
    'setup_help'       => 'Enter the 6-digit code generated by the app to enable protection on your account.',
    'setup_step_1'     => '1. Scan the QR code with your authenticator app.',
    'setup_step_2'     => '2. Enter the 6-digit code your app generates.',
    'manual_secret'    => 'Can\'t scan? Enter this code manually:',
    'btn_copy_secret'  => 'Copy code',
    'secret_copied'    => 'Code copied to clipboard.',
    'code_label'       => '6-digit code',
    'code_aria_label'  => 'Two-factor verification code',
    'code_placeholder' => '000000',
    'btn_confirm'      => 'Confirm and enable',
    'btn_regenerate'   => 'Generate new QR code',
    'regenerated'      => 'New QR code generated. Scan it again with your authenticator app.',
    'btn_cancel'       => 'Cancel',
    'enabled'          => 'Two-factor authentication enabled.',
    'verified'         => 'Code verified.',

    // Recovery codes (after confirm)
    'recovery_title'    => 'Recovery codes',
    'recovery_subtitle' => 'Save these codes before continuing',
    'recovery_intro'    => 'Save these codes in a safe place (password manager, vault, paper). Each code can be used ONCE if you lose access to your authenticator app.',
    'recovery_warning'  => 'This is the only time these codes will be shown. If you lose them and lose access to the app, you will lose access to your account.',
    'btn_copy'          => 'Copy all',
    'btn_download'      => 'Download as file',
    'btn_done'          => 'I saved them. Continue',
    'copied'            => 'Codes copied to clipboard.',
    'copy_failed'       => 'Could not copy automatically. Select the codes and copy them manually.',
    'downloaded'        => 'File generated. Keep it somewhere safe.',

    // Verify (login flow)
    'verify_title'              => 'Two-factor verification',
    'verify_subtitle'           => 'One last step before you sign in',
    'verify_intro'              => 'Open your authenticator app and enter the current code. If you no longer have access, use a recovery code.',
    'verify_hint_totp'          => 'Open your authenticator app (Google or Microsoft Authenticator) and check the 6-digit code shown right now.',
    'verify_hint_recovery'      => 'Enter one of the recovery codes you saved when enabling two-factor authentication. Each code works only once.',
    'verify_help'               => 'Enter the code below to finish signing in.',
    'verify_use_recovery'       => 'Use recovery code',
    'verify_use_totp'           => 'Use authenticator app',
    'recovery_code_label'       => 'Recovery code (format XXXX-XXXX)',
    'recovery_code_aria_label'  => 'Recovery code',
    'recovery_code_placeholder' => 'XXXX-XXXX',
    'btn_verify'                => 'Verify',

    // Feedback and shared actions
    'invalid_code'      => 'Invalid or expired code.',
    'network_error'     => 'Network error. Please try again.',
    'too_many_attempts' => 'Too many attempts. Wait a minute and try again.',
    'session_expired'   => 'Your session has expired. Reload the page and sign in again.',
    'btn_logout'        => 'Log out',
];
