/**
 * jQuery global bridge for Vite modules.
 *
 * jQuery is pre-loaded as a synchronous <script> in app.blade.php <head>
 * (public/js/jquery.min.js) so that inline scripts generated by Yajra
 * DataTables ($dataTable->scripts()) can use $ before ES modules run.
 *
 * This module just re-exports the already-defined global so Vite-bundled
 * plugins (DataTables, jQuery plugins, etc.) share the same instance.
 *
 * NOTE: We still import the npm package so Vite bundles jQuery for pages
 * that don't use the static <script> (e.g. auth pages). jQuery's UMD wrapper
 * detects window.jQuery and reuses the existing instance.
 */
import '../../node_modules/jquery/dist/jquery.js';

const jQuery = window.jQuery;
window.$ = jQuery;

export default jQuery;
