/**
 * Textos/linhas de exemplo para os testes da tela de Faturamento (subconjunto
 * de lang/pt_BR/financial_billing.php — só o que os testes afirmam).
 */
export const t = {
    title: 'Faturamento TISS',
    btn_glosas: 'Conciliação de glosas',
    btn_import_return: 'Importar retorno',
    kpis_label: 'Indicadores do faturamento no período',
    kpi_to_bill: 'A faturar',
    kpi_to_bill_hint: 'Atendimentos marcados como Atendido no período e ainda sem guia ativa.',
    kpi_to_bill_estimate: '≈ :amount pela tabela de preços',
    kpi_to_bill_estimate_partial: '≈ :amount (:priced de :count com preço na tabela)',
    kpi_to_bill_no_estimate: 'Sem preço na tabela para estimar',
    kpi_attendances: ':count atendimento(s)',
    kpi_open: 'Em aberto',
    kpi_open_hint: 'Guias enviadas ainda sem recebimento nem glosa.',
    kpi_received: 'Recebido',
    kpi_received_hint: 'Valor recebido das guias pagas.',
    kpi_denied: 'Glosado',
    kpi_denied_hint: 'Valor glosado nas guias.',
    kpi_denied_link: 'Abrir conciliação',
    kpi_tiss_pending: 'Pendências TISS',
    kpi_tiss_pending_hint: 'Guias TISS em aberto fora de um lote TISS.',
    kpi_claims_count: ':count guia(s)',
    flow_label: 'Como funciona o faturamento',
    flow_steps: {
        attendance: { title: 'Atendimento', hint: 'Marcado como Atendido na agenda' },
        claim:      { title: 'Guia', hint: 'Individual ou em lote' },
        batch:      { title: 'Lote', hint: 'Guias do mesmo convênio' },
        submit:     { title: 'Envio', hint: 'XML TISS para a operadora' },
        settle:     { title: 'Recebimento/Glosa', hint: 'Registre o pagamento ou a glosa' },
    },
    filters_label: 'Filtros do faturamento',
    filter_covenant: 'Convênio',
    filter_covenant_all: 'Todos os convênios',
    filter_claim_status: 'Status das guias',
    filter_status_all: 'Todos os status',
    filter_all: 'Todos',
    filter_tiss_pending: 'Pendência TISS (fora de lote)',
    filter_batch: 'Lote :code',
    filter_batch_clear: 'Remover o filtro do lote :code',
    filter_clear: 'Limpar filtros',
    filter_hint: 'O período e o convênio valem para as três abas.',
    filtering: 'Atualizando…',
    tabs_label: 'Etapas do faturamento',
    tab_eligible: 'A faturar',
    tab_claims: 'Guias',
    tab_batches: 'Lotes',
    search_eligible: 'Buscar paciente',
    search_claims: 'Buscar por paciente, guia (GUI), lote (LOT) ou nº TISS',
    search_batches: 'Buscar por lote (LOT), nº do lote TISS, guia ou paciente',
    search_clear: 'Limpar busca',
    search_no_results: 'Nenhum resultado para “:term”.',
    sort_by: 'Ordenar por :column',
    pagination_label: 'Paginação da aba :tab',
    pagination_showing: 'Exibindo',
    pagination_of: 'de',
    pagination_previous: 'Página anterior',
    pagination_next: 'Próxima página',
    pagination_suffix: { eligible: 'atendimentos', claims: 'guias', batches: 'lotes' },
    row_actions_claim: 'Mais ações da guia :code',
    row_actions_batch: 'Mais ações do lote :code',
    action_fix_pending: 'Corrigir pendência',
    action_cancel_claim: 'Cancelar guia',
    action_cancel_batch: 'Cancelar lote',
    cancelled_on: 'Cancelada em :date',
    cancelled_on_by: 'Cancelada em :date por :user',
    batch_cancelled_on: 'Lote cancelado em :date',
    batch_cancelled_on_by: 'Lote cancelado em :date por :user',
    cancel_reason_value: 'Motivo: :reason',
    cancel_claim_title: 'Cancelar a guia :code',
    cancel_claim_message: 'Só guia em rascunho pode ser cancelada.',
    cancel_claim_confirm: 'Cancelar guia',
    cancel_batch_title: 'Cancelar o lote :code',
    cancel_batch_message: 'Todas as guias em rascunho do lote são canceladas.',
    cancel_batch_confirm: 'Cancelar lote',
    fix_title: 'Corrigir pendência da guia',
    fix_intro: 'Corrija os dados da guia TISS e salve.',
    fix_summary_guide: 'Guia',
    fix_summary_tiss_number: 'Nº guia TISS',
    fix_summary_patient: 'Paciente',
    fix_card_number: 'Carteirinha (nº do cartão do beneficiário)',
    fix_card_number_hint: 'Exatamente como no cartão do plano de saúde.',
    fix_authorization: 'Nº da autorização',
    fix_authorization_hint: 'Obrigatório quando o convênio exige autorização prévia.',
    fix_beneficiary_hint: 'Se o nome do beneficiário estiver vazio, é preenchido com o do paciente.',
    btn_fix_save: 'Salvar e validar',
    fix_result_title: 'Resultado da pré-validação',
    fix_failed: 'Não foi possível salvar a correção. Tente novamente.',
    errors_label: 'Erros',
    warnings_label: 'Avisos',
    pending_no_issues: 'Nenhuma pendência encontrada.',
    col_date: 'Data',
    col_patient: 'Paciente',
    col_doctor: 'Médico',
    col_covenant: 'Convênio',
    col_visit_type: 'Tipo',
    col_actions: 'Ações',
    col_suggested_price: 'Valor (tabela)',
    col_guide: 'Guia',
    col_tiss_number: 'Nº guia TISS',
    col_attendance: 'Atendimento',
    col_batch: 'Lote',
    col_status: 'Status',
    col_amount: 'Valor',
    col_glosa: 'Glosa',
    col_received: 'Pago',
    col_period: 'Período',
    col_guides: 'Guias',
    col_total: 'Total',
    col_submitted_at: 'Enviado em',
    not_submitted: 'Não enviado',
    no_covenant: 'Sem convênio',
    eligible_select_all: 'Selecionar todos os atendimentos listados',
    eligible_select_row: 'Selecionar :patient — :date',
    eligible_selected: ':count selecionado(s)',
    btn_new_batch: 'Novo lote',
    btn_bill_selected: 'Gerar lote com :count selecionado(s)',
    btn_bill: 'Guia individual',
    btn_bill_label: 'Gerar guia individual de :patient',
    no_eligible: 'Nenhum atendimento a faturar no período.',
    batch_link_label: 'Ver o lote :code na aba Lotes',
    no_claims: 'Nenhuma guia encontrada.',
    pending_badge: 'Pendência',
    pending_badge_hint: 'Guia com pendência TISS.',
    out_of_batch_badge: 'Fora de lote',
    out_of_batch_hint: 'Guia TISS individual: precisa entrar num lote para ser enviada à operadora.',
    out_of_batch_notice: 'Guias TISS "Fora de lote" ainda não foram enviadas.',
    action_check_pending: 'Verificar pendências TISS',
    action_receive: 'Registrar recebimento',
    action_deny: 'Marcar como glosada',
    action_view_claims: 'Ver as guias do lote :code',
    batch_guides_included: ':count no lote',
    batch_guides_pending: ':count com pendência',
    particular_badge: 'Particular',
    action_submit_tiss: 'Enviar à operadora',
    action_mark_charged: 'Marcar como cobrado',
    action_download_xml: 'Baixar XML TISS',
    submit_confirm_title_tiss: 'Enviar lote à operadora',
    submit_confirm_title_particular: 'Marcar lote como cobrado',
    submit_confirm_intro_tiss: 'Confira o resumo.',
    submit_confirm_intro_particular: 'Lote particular não vai para a operadora.',
    summary_batch: 'Lote',
    summary_operator: 'Operadora',
    summary_covenant: 'Convênio',
    summary_guides: 'Guias',
    summary_total: 'Total',
    summary_period: 'Período',
    summary_period_value: ':from a :to',
    summary_guides_value: ':count guia(s)',
    summary_pending_warning: ':count guia(s) com pendência não será(ão) enviada(s).',
    btn_cancel: 'Cancelar',
    btn_close: 'Fechar',
    dismiss: 'Fechar aviso',
    new_tab: '(abre em nova aba)',
    processing: 'Processando...',
    discard_title: 'Descartar o que foi digitado?',
    btn_keep_editing: 'Continuar editando',
    btn_discard: 'Descartar',
    individual_title: 'Guia individual',
    individual_tiss_hint: 'Guia TISS individual precisa entrar num lote para ser enviada à operadora.',
    quantity: 'Quantidade',
    unit_price: 'Valor unitário',
    claim_total: 'Total da guia',
    claim_total_formula: ':quantity × :unit',
    suggested_price_hint: 'Preço da tabela (:procedure × :covenant): :amount.',
    suggested_price_short: 'Preço da tabela: :amount.',
    suggested_price_none: 'Sem preço na tabela para este procedimento e convênio.',
    suggested_price_mixed: 'Os atendimentos deste lote têm preços diferentes na tabela (:min a :max); o lote usa um único valor unitário.',
    suggested_price_batch: 'Preço da tabela para os atendimentos do lote: :amount.',
    suggested_price_use: 'Usar :amount',
    price_table_link: 'Abrir a tabela de preços',
    clinical_indication: 'CID (indicação clínica)',
    clinical_indication_hint: 'Obrigatório para a guia entrar no lote TISS sem pendência.',
    cid_placeholder: 'Busque por código ou diagnóstico',
    batch_title: 'Novo lote',
    batch_quantity: 'Quantidade por guia',
    batch_hint_selected: ':count atendimento(s) marcado(s) deste convênio entrarão no lote.',
    batch_hint_excluded: ':count marcado(s) de outro convênio ficarão de fora.',
    batch_hint_all: 'Nenhum atendimento marcado: o lote incluirá todos os atendimentos elegíveis do convênio no período (:count na lista atual).',
    batch_hint_pick: 'Escolha o convênio do lote.',
    batch_estimated_total: 'Total estimado: :total',
    batch_estimated_formula: ':count guia(s) × :quantity × :unit',
    particular_hint: 'Convênio sem registro ANS.',
    receipt_title: 'Registrar recebimento',
    receipt_partial_hint: 'Recebimento parcial: :difference a menos que o esperado.',
    receipt_glosa_reversed_hint: 'Valor acima do esperado: :amount da glosa será considerado revertido (ex.: recurso aceito).',
    btn_confirm_receipt: 'Registrar recebimento',
    deny_title: 'Marcar guia como glosada',
    deny_summary_guide: 'Guia',
    deny_summary_patient: 'Paciente',
    deny_summary_amount: 'Valor da guia',
    deny_type_legend: 'Tipo de glosa',
    deny_type_total: 'Total (:amount)',
    deny_type_partial: 'Parcial',
    deny_amount: 'Valor glosado',
    deny_amount_hint: 'Glosa parcial: informe só a parte recusada. Restante a receber: :remaining',
    deny_amount_limit: 'Maior que zero e até :max (valor da guia).',
    deny_amount_required: 'Informe o valor glosado.',
    deny_amount_min: 'O valor glosado deve ser maior que zero.',
    deny_amount_max: 'O valor glosado não pode ser maior que o valor da guia (:max).',
    deny_effect_hint: 'A guia passa para Glosada e o atendimento volta a aparecer em "A faturar".',
    deny_effect_hint_partial: 'Glosa parcial: a guia passa para Glosada com :remaining ainda a receber. Registre esse recebimento antes de refaturar o atendimento.',
    btn_confirm_deny: 'Confirmar glosa',
    deny_done_title: 'Glosa registrada',
    denied_next_step: 'Glosa registrada na guia :code. Próximo passo: abrir o recurso na Conciliação de glosas.',
    denied_particular: 'Glosa registrada na guia :code. Guia particular (sem TISS) não gera recurso na Conciliação de glosas.',
    btn_open_conciliation: 'Abrir conciliação',
    pending_check_failed: 'Não foi possível verificar as pendências desta guia. Tente novamente.',
    unexpected_error: 'Não foi possível concluir a ação. Tente novamente.',
    import_return_title: 'Importar retorno TISS',
    // Fase 4 (parte 2): ações em lote.
    action_attach_claim: 'Incluir em lote',
    action_add_claims: 'Adicionar guias',
    action_reprocess_pending: 'Reprocessar pendentes',
    action_receive_batch: 'Registrar recebimento',
    action_receive_batch_label: 'Registrar recebimento do lote :code',
    claims_select_page: 'Selecionar as guias desta página que podem receber pagamento',
    claims_select_row: 'Selecionar a guia :code — :patient',
    selection_bar_label: 'Guias selecionadas para registrar recebimento',
    selection_summary: ':count selecionada(s) · :total',
    selection_other_pages: 'Inclui guias de outras páginas.',
    btn_bulk_receive: 'Registrar recebimento',
    btn_clear_selection: 'Limpar seleção',
    receipt_paid_at: 'Data do recebimento',
    receipt_payment_method: 'Forma de pagamento',
    receipt_notes: 'Observação',
    receipt_cash_hint: 'O valor entra automaticamente no fluxo de caixa.',
    bulk_receipt_title: 'Registrar recebimento de :count guia(s)',
    bulk_receipt_intro: 'Um lançamento de caixa por guia.',
    bulk_receipt_col_guide: 'Guia',
    bulk_receipt_col_patient: 'Paciente',
    bulk_receipt_col_amount: 'Valor da guia',
    bulk_receipt_col_receivable: 'A receber',
    bulk_receipt_col_paid: 'Valor recebido',
    bulk_receipt_amount_label: 'Valor recebido da guia :code',
    bulk_receipt_amount_invalid: 'Informe um valor maior que zero e até :max.',
    bulk_receipt_total: 'Total a registrar',
    bulk_receipt_over_limit: 'Selecione no máximo :max guias por vez.',
    bulk_receipt_confirm: 'Registrar :count recebimento(s)',
    bulk_receipt_errors_title: 'Nada foi gravado. Corrija e tente de novo:',
    bulk_receipt_failed: 'Não foi possível registrar os recebimentos. Tente novamente.',
    bulk_receipt_result_title: 'Resultado',
    bulk_receipt_paid_total: 'Total registrado: :total',
    bulk_receipt_skipped_title: 'Ignoradas',
    batch_receipt_title: 'Registrar recebimento do lote :code',
    batch_receipt_intro: 'As guias do lote que podem receber pagamento são pagas pelo valor a receber.',
    batch_receipt_loading: 'Calculando as guias a receber…',
    batch_receipt_preview: ':count guia(s) a receber · :total',
    batch_receipt_blocked: ':count guia(s) em aberto não entram.',
    batch_receipt_over_limit: 'O lote tem :count guias a receber; o limite por vez é :max.',
    batch_receipt_confirm: 'Registrar recebimento',
    batch_receipt_failed: 'Não foi possível carregar a prévia do lote. Tente novamente.',
    add_claims_title: 'Adicionar guias ao lote :code',
    add_claims_intro: 'Guias TISS em rascunho do mesmo convênio fora de lote TISS.',
    add_claims_loading: 'Carregando as guias elegíveis…',
    add_claims_empty: 'Nenhuma guia elegível para este lote.',
    add_claims_select_all: 'Selecionar todas as guias listadas',
    add_claims_select_row: 'Selecionar a guia :code — :patient',
    add_claims_origin_individual: 'Individual',
    add_claims_origin_this: 'Pendente neste lote',
    add_claims_origin_other: 'Pendente no lote :code',
    add_claims_truncated: 'Mostrando as primeiras :shown de :total guias elegíveis.',
    add_claims_selected: ':count selecionada(s)',
    add_claims_confirm: 'Adicionar :count guia(s)',
    add_claims_failed: 'Não foi possível anexar as guias. Tente novamente.',
    add_claims_load_failed: 'Não foi possível carregar as guias. Tente novamente.',
    reprocess_title: 'Reprocessar pendências do lote :code',
    reprocess_intro: 'A pré-validação roda de novo nas :count guia(s) com pendência deste lote.',
    reprocess_confirm: 'Reprocessar',
    attach_title: 'Incluir a guia :code em um lote',
    attach_intro: 'Escolha um lote em rascunho do mesmo convênio.',
    attach_targets_legend: 'Lotes em rascunho do convênio',
    attach_target_label: ':code — :count guia(s) · :period',
    attach_target_current: 'lote atual da guia',
    attach_loading: 'Carregando os lotes…',
    attach_no_targets: 'Nenhum lote em rascunho deste convênio aceita a guia agora.',
    attach_confirm: 'Incluir no lote',
    attach_result_title: 'Resultado por guia',
    attach_result_attached: 'Incluída no lote',
    attach_result_pending: 'Ficou de fora',
    attach_result_clean: 'Sem pendências.',
    shared: {
        period: {
            label: 'Período',
            from: 'De',
            to: 'Até',
            invalid_range: 'A data inicial deve ser anterior ou igual à final.',
            invalid_date: 'Informe uma data válida.',
            after_max: 'A data não pode ser posterior a :date.',
            presets: {
                today: 'Hoje', yesterday: 'Ontem', last7: 'Últimos 7 dias', month: 'Mês atual',
                last_month: 'Mês anterior', year: 'Ano atual', custom: 'Personalizado',
            },
        },
    },
};

export function claim(overrides = {}) {
    return {
        id: 'c1',
        code: 'GUI-0001',
        guide_number: 'GUI-0001',
        attendance_date: '2026-09-20',
        patient_name: 'Maria Souza',
        doctor_name: 'Dr. Paulo',
        covenant_name: 'Unimed',
        batch_id: 'b1',
        batch_code: 'LOT-0001',
        status: 'submitted',
        status_label: 'Enviado',
        status_badge: 'badge-soft-info',
        amount: 200,
        glosa_amount: 0,
        paid_amount: 0,
        receivable_amount: 200,
        is_tiss: true,
        has_pending_guide: false,
        out_of_batch: false,
        pre_validate_url: '/pre-validate/g1',
        allowed_actions: ['pay', 'deny'],
        mark_paid_url: '/claims/c1/paid',
        mark_denied_url: '/claims/c1/denied',
        cancel_url: '/claims/c1/cancel',
        fix_pending: null,
        cancelled_at: null,
        cancelled_by_name: null,
        cancel_reason: null,
        ...overrides,
    };
}

export function batch(overrides = {}) {
    return {
        id: 'b1',
        code: 'LOT-0007',
        created_at: '2026-09-20T10:00:00-03:00',
        submitted_at: null,
        period_start: '2026-09-01',
        period_end: '2026-09-20',
        covenant_name: 'Unimed',
        claims_count: 3,
        included_count: 2,
        pending_count: 1,
        total_amount: 450,
        status: 'draft',
        status_label: 'Rascunho',
        status_badge: 'badge-soft-secondary',
        is_tiss: true,
        is_particular: false,
        notes: null,
        allowed_actions: ['submit', 'download_xml'],
        submit_url: '/batches/b1/submit',
        xml_url: '/batches/b1/xml',
        cancel_url: '/batches/b1/cancel',
        cancelled_at: null,
        cancelled_by_name: null,
        cancel_reason: null,
        ...overrides,
    };
}

export function schedule(overrides = {}) {
    return {
        id: 's1',
        date_time: '2026-09-20T09:30:00-03:00',
        patient_name: 'João Lima',
        doctor_name: 'Dra. Ana',
        covenant_name: 'Unimed',
        covenant_id: 'cov-1',
        visit_type: 'Consulta',
        procedure_name: null,
        suggested_price: null,
        ...overrides,
    };
}

/**
 * Paginator do Laravel (formato que o Inertia serializa) com as linhas dadas.
 * `pageName` monta links realistas (?claims_page=2...).
 */
export function paginate(data, overrides = {}, pageName = 'page') {
    const currentPage = overrides.current_page ?? 1;
    const lastPage    = overrides.last_page ?? 1;
    const url         = (page) => `/panel/financial/billing?${pageName}=${page}`;
    const numbers     = Array.from({ length: lastPage }, (_, i) => ({
        url: url(i + 1), label: String(i + 1), active: i + 1 === currentPage,
    }));

    return {
        data,
        current_page:  currentPage,
        last_page:     lastPage,
        per_page:      50,
        from:          data.length ? 1 : null,
        to:            data.length || null,
        total:         overrides.total ?? data.length,
        prev_page_url: currentPage > 1 ? url(currentPage - 1) : null,
        next_page_url: currentPage < lastPage ? url(currentPage + 1) : null,
        links: [
            { url: currentPage > 1 ? url(currentPage - 1) : null, label: '&laquo; Anterior', active: false },
            ...numbers,
            { url: currentPage < lastPage ? url(currentPage + 1) : null, label: 'Próxima &raquo;', active: false },
        ],
        ...overrides,
    };
}

/** `lists` do servidor (busca/ordem aplicadas por aba) com os padrões. */
export function lists(overrides = {}) {
    return {
        eligible: { search: '', sort: 'date', direction: 'asc', default_sort: 'date', default_direction: 'asc', ...(overrides.eligible ?? {}) },
        claims:   { search: '', sort: 'created', direction: 'desc', default_sort: 'created', default_direction: 'desc', ...(overrides.claims ?? {}) },
        batches:  { search: '', sort: 'created', direction: 'desc', default_sort: 'created', default_direction: 'desc', ...(overrides.batches ?? {}) },
    };
}

export const kpis = {
    to_bill:      { count: 12, priced_count: 10, estimated_amount: 1500 },
    open:         { count: 3, amount: 450 },
    received:     { count: 5, amount: 980.5 },
    denied:       { count: 2, amount: 120 },
    tiss_pending: { count: 4 },
};

/** Formato de moeda esperado (mesmo Intl que useLocaleFormat usa em pt-BR). */
export function brl(value) {
    return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value);
}

/** Normaliza espaços (o Intl usa espaço não separável entre "R$" e o valor). */
export function norm(text) {
    return String(text ?? '').replace(/\s+/g, ' ').trim();
}
