[program:easyeye-worker-default]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/app/artisan queue:work %(ENV_SUPERVISOR_QUEUE_CONNECTION)s --queue=default,high --timeout=90 --tries=3 --sleep=3 --max-jobs=1000
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=%(ENV_SUPERVISOR_WORKER_USER)s
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/easyeye-default.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stopwaitsecs=100
